"""create users and posts tables

Revision ID: 5ff348b4b0b9
Revises: 
Create Date: 2025-08-31 22:51:31.005626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff348b4b0b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index('idx_user_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_status_scheduled_time', ['status', 'scheduled_time'], unique=False)
        batch_op.create_index('idx_user_scheduled_time', ['user_id', 'scheduled_time'], unique=False)

    op.create_table('user_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['social_platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_platforms', schema=None) as batch_op:
        batch_op.create_index('idx_token_expiry', ['token_expiry'], unique=False)
        batch_op.create_index('idx_user_platform', ['user_id', 'platform_id'], unique=False)
        batch_op.create_index('idx_user_platform_unique', ['user_id', 'platform_id', 'platform_user_id'], unique=True)

    op.create_table('post_media',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'media_id')
    )
    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.create_index('idx_media_id', ['media_id'], unique=False)
        batch_op.create_index('idx_post_sort_order', ['post_id', 'sort_order'], unique=False)

    op.create_table('post_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_caption', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['social_platforms.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_platforms', schema=None) as batch_op:
        batch_op.create_index('idx_platform_post_id', ['platform_post_id'], unique=False)
        batch_op.create_index('idx_post_platform_unique', ['post_id', 'platform_id'], unique=True)
        batch_op.create_index('idx_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_platforms', schema=None) as batch_op:
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_post_platform_unique')
        batch_op.drop_index('idx_platform_post_id')

    op.drop_table('post_platforms')
    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.drop_index('idx_post_sort_order')
        batch_op.drop_index('idx_media_id')

    op.drop_table('post_media')
    with op.batch_alter_table('user_platforms', schema=None) as batch_op:
        batch_op.drop_index('idx_user_platform_unique')
        batch_op.drop_index('idx_user_platform')
        batch_op.drop_index('idx_token_expiry')

    op.drop_table('user_platforms')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_user_scheduled_time')
        batch_op.drop_index('idx_status_scheduled_time')

    op.drop_table('posts')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('idx_user_created_at')

    op.drop_table('media')
    op.drop_table('users')
    op.drop_table('social_platforms')
    # ### end Alembic commands ###
